### PR TITLE
xp005 gras

### PR DESCRIPTION
**Pull request by simonfojtu**

### CODE REVIEW

**Comment by firepick1** [comment]
Simon,

That graph is very interesting. I am curious why C++ is so different from
MatLab for same GRAS algorithm. :)

Karl

On Tuesday, February 17, 2015, Šimon Fojtů notifications@github.com wrote:

> Merged #3 https://github.com/firepick1/fpd-vision/pull/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firepick1/fpd-vision/pull/3#event-237239011.

## 

Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Comment by simonfojtu** [comment]
Karl,

the difference is in the conversion from color to grayscale image in Matlab
and OpenCV.

Simon

**Comment by simonfojtu** [comment]
Ok, and also in the diff function of Matlab, which was not working
correctly with uint8 numbers. I've updated the figure. Now the difference
is only due to the conversion.

Simon

**Comment by firepick1** [comment]
Simon,

Ahhhhhhhh!

That is so cool!

I have bad eyesight and I notice that reds and blues are in different focus
for my own eyes. Now I totally understand why the color Matlab graph had
several peaks. For FirePick, a grayscale image seems more practical.

Thanks for the clarification.

:D Karl

On Wed, Feb 18, 2015 at 1:50 AM, Šimon Fojtů notifications@github.com
wrote:

> Ok, and also in the diff function of Matlab, which was not working
> correctly with uint8 numbers. I've updated the figure. Now the difference
> is only due to the conversion.
> 
> Simon
> 
> On Wed, Feb 18, 2015 at 10:38 AM, Šimon Fojtů simon.fojtu@gmail.com
> wrote:
> 
> > Karl,
> > 
> > the difference is in the conversion from color to grayscale image in
> > Matlab and OpenCV.
> > 
> > Simon
> > 
> > On Wed, Feb 18, 2015 at 6:52 AM, firepick1 notifications@github.com
> > wrote:
> > 
> > > Simon,
> > > 
> > > That graph is very interesting. I am curious why C++ is so different
> > > from
> > > MatLab for same GRAS algorithm. :)
> > > 
> > > Karl
> > > 
> > > On Tuesday, February 17, 2015, Šimon Fojtů notifications@github.com
> > > wrote:
> > > 
> > > > Merged #3 https://github.com/firepick1/fpd-vision/pull/3.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/firepick1/fpd-vision/pull/3#event-237239011.
> > > 
> > > ## 
> > > 
> > > Karl Lew
> > > FIREPICK SERVICES LLC
> > > karl@firepick.org
> > > www.firepick.org
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/firepick1/fpd-vision/pull/3#issuecomment-74816783.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firepick1/fpd-vision/pull/3#issuecomment-74838164.

## 

Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Pull request merged**
